name: Run Go Unit Tests

on:
  push:
  pull_request:
  workflow_dispatch:  # Enables manual trigger

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: cloud_webserver_v2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install libhdf5-dev
        run: sudo apt-get update && sudo apt-get install -y libhdf5-dev && sudo apt-get install -y libhdf5-serial-dev

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'cloud_webserver_v2/go.mod'

      - name: Download dependencies
        run: go mod tidy

      - name: Run unit tests
        run: go test ./... -v
